# .github/workflows/my-project.yml
name: My project

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Install Tuist
        run: brew install tuist
      - name: Install iOS Simulator
        run: xcrun simctl create 'iPhone 14 Pro Max' com.apple.CoreSimulator.SimDeviceType.iPhone-14-Pro-Max com.apple.CoreSimulator.SimRuntime.iOS-16-2
      - name: Run Tuist build
        run: make test
