name: Tuist Test

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "14.3.1"
      - name: Install Tuist
        run: brew install tuist
      - name: Run Tuist build
        run: make test
